const appname = "eMart";
const appversion = "Version 1.0.0";
const credits = "Măng Hầm Rau Cải";
const email = "Email";
const emailHint = "admin@admin.com";
const password = "Password";
const passwordHint = "********";
const retypePassword = "Retype Password";
const name = "Name";
const nameHint = "Măng Hầm Rau cải";
const forgetPassword = "Forget Passowrd";
const login = "Log in";
const signup = "Sign Up";
const createNewAccount = "or, creare new account";
const loginWith = "Log in with";
const privacyPolicy = "Privacy Policy";
const temAndCond = "Terms and Conditions";
const alreadyHaveAccount = "Already have an account? ";
const home = "Home",
    categories = "Categories",
    cart = "Cart",
    account = "Account";
const searchanything = "Search anything...",
    todayDeal = "Today's Deal",
    flashsale = "Flash Sale",
    topSellers = "Top Sellers",
    brand = "Brand",
    topCaregories = "Top Categories",
    featuredCategories = "Featured Categories",
    womenDress = "Women Dress",
    girlsDress = "Girls Dresses",
    girlsWatches = "Girls Watches",
    mobilePhone = "Mobile Phone",
    boysGlasses = "Boys Glasses",
    featuredProduct = "Featured Products",
    tShirts = "T-Shirts";

const womenClothing = "Women Clothing",
    menClothingFashion = "Men Clothing & Fashion",
    compAcesses = "Computer & Acessories",
    automobile = "Automobile",
    kidtoys = "Kids & Toys",
    sports = "Sports",
    jewelery = "Jewelery",
    cellphone = "Cellphone & Tab",
    funiture = "Funiture";
